submission made

diff --git a/turnip-submit b/turnip-submit
--- a/turnip-submit
+++ b/turnip-submit
@@ -53,7 +53,7 @@ validate_zid() {
 # then checks if a file exists at the given path
 validate_tests_filepath() {
     if ! echo "$1" | grep -qE '^[a-zA-Z0-9_./-]+$'; then
-        echo "turnip-add: invalid filename: $1" >&2
+        echo "turnip-submit: invalid filename: $1" >&2
         exit 1
     fi
 
